# Generated by Django 5.2.16 on 2026-07-16 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('operating_system', models.CharField(max_length=100)),
                ('cpu_usage', models.IntegerField(default=0)),
                ('memory_usage', models.IntegerField(default=0)),
                ('storage_usage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Warning', 'Warning')], default='Online', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Running', 'Running'), ('Failed', 'Failed')], default='Success', max_length=20)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='dashboard.server')),
            ],
        ),
    ]
